source "https://rubygems.org"
ruby "3.1.4"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.7"
gem "rack-cors"
gem "redis", "~> 5.0"
gem "httparty"
gem "dotenv-rails"
gem "rack-attack", "~> 6.7"
gem "lograge", "~> 0.13"
gem "faraday", "~> 2.0"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails", "~> 6.4"
  gem "faker", "~> 3.2"
  gem "pry-rails"
  gem "database_cleaner-active_record"
end

group :test do
  gem "shoulda-matchers", "~> 5.3"
  gem "simplecov", require: false
  gem "webmock"
  gem "vcr"
end

group :development do
  gem "listen", "~> 3.8"
  gem "spring"
  gem "spring-commands-rspec"
end
